### PR TITLE
Created categories; moved files; updated root README.md

### PR DESCRIPTION
**Pull request by AgedLace**

### CODE REVIEW

**Comment by Arthurauthor** [comment]
And could Conferences be under Career resources?

**Comment by AgedLace** [comment]
I don't see a problem combining Motivational / Inspirational.  The Conferences one could actually be any type, not just job / career related.  Several people specifically requested to have a separate podcast category, so we can ask in #resource-treasures to see what people want.

Good suggestions!  Keep em coming!

**Comment by Arthurauthor** [comment]
Yeah, sure - The conferences is probably a good stand alone.  If podcast is popular, sure lets do it.  I reckon there are a lot of resources that will be useful to post in multiple categories anyway.
I figure we go with what we have. we can always move stuff later.

**Comment by AgedLace** [comment]
Works for me ... thanks!

**Pull request merged**
